language: php
php:
  - 7.1
  - 7.2
  - 7.3
os:
  - linux
install:
 - cp app/config/parameters-docker.yml app/config/parameters.yml
 - composer install
 - npm install
#JS tools installed by npm required for validation only, not for app execution or development
script: vendor/bin/phing -f phing.xml test-all

branches:
  only:
    - gh-pages
    - /.*/
