language: php
php:
  - 7.1
  - 7.0
  - 5.6
#  - hhvm
  - nightly
os:
  - linux
# osx/php testing not supported by travis
before_script:
  - mysql -e 'create database travis_app_test DEFAULT CHARACTER SET utf8mb4 collate utf8mb4_unicode_ci;'
install:
 - cp app/config/parameters-docker.yml app/config/parameters.yml
 - composer install
 - npm install
#JS tools installed by npm required for validation only, not for app execution or development
script: vendor/bin/phing -f phing.xml test-all
#Disable nightly-build test until I fix deps
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

branches:
  only:
    - gh-pages
    - /.*/
