language: php
php:
  - 5.6
  - 5.5
  - hhvm
  - nightly
os:
  - linux
# osx/php testing not supported by travis
install:
 - composer install
 - npm install
#JS tools installed by npm required for validation only, not for app execution or development
script: vendor/bin/phing test-all
#Disable nightly-build test until I fix deps
matrix:
  allow_failures:
    - php: nightly
