language: php
php:
  - 5.6
  - 5.5
  - hhvm
  - nightly
os:
  - linux
# osx/php testing not supported by travis
install: composer install
script: vendor/bin/phing
#Disable nightly-build test until I fix deps
matrix:
  allow_failures:
    - php: nightly
