# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment
image: parsingphase/php-73-build

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - cp app/config/parameters-docker.yml app/config/parameters.yml
          - composer install
          - npm install
          - TRAVIS=1 ./vendor/bin/phing -f phing.xml test-all
