index:
    path:     /
    defaults: { _controller: TakeATicketBundle:Default:index }
    methods:  [GET]

songSearch:
    path:     /songSearch
    defaults: { _controller: TakeATicketBundle:Default:songSearch }
    methods:  [GET]

upcomingRss:
    path:     /upcomingRss
    defaults: { _controller: TakeATicketBundle:Rss:upcomingRss }
    methods:  [GET]

nextSongAjax:
    path: /api/next
    defaults: { _controller: TakeATicketBundle:Ajax:nextSongs }
    methods:  [GET]

songSearchAjax:
    path: /api/songSearch
    defaults: { _controller: TakeATicketBundle:Ajax:songSearch }
    methods:  [GET,POST]

remotesRedirectAjax:
    path: /api/remotesRedirect
    defaults: { _controller: TakeATicketBundle:Ajax:remotesRedirect }
    methods:  [GET]

manage:
    path:     /manage
    defaults: { _controller: TakeATicketBundle:Management:index }
    methods:  [GET]

