index:
    path:     /
    defaults: { _controller: TakeATicketBundle:Default:index }
    methods:  [GET]

songSearch:
    path:     /songSearch
    defaults: { _controller: TakeATicketBundle:Default:songSearch }
    methods:  [GET]

upcomingRss:
    path:     /upcomingRss
    defaults: { _controller: TakeATicketBundle:Rss:upcomingRss }
    methods:  [GET]

nextSongAjax:
    path: /api/next
    defaults: { _controller: TakeATicketBundle:Ajax:nextSongs }
    methods:  [GET]

songSearchAjax:
    path: /api/songSearch
    defaults: { _controller: TakeATicketBundle:Ajax:songSearch }
    methods:  [GET,POST]

remotesRedirectAjax:
    path: /api/remotesRedirect
    defaults: { _controller: TakeATicketBundle:Ajax:remotesRedirect }
    methods:  [GET]

saveTicketAjax:
    path: /api/saveTicket
    defaults: { _controller: TakeATicketBundle:Ajax:saveTicket }
    methods:  [POST]

useTicketAjax:
    path: /api/useTicket
    defaults: { _controller: TakeATicketBundle:Ajax:useTicket }
    methods:  [POST]

deleteTicketAjax:
    path: /api/deleteTicket
    defaults: { _controller: TakeATicketBundle:Ajax:deleteTicket }
    methods:  [POST]

manage:
    path:     /manage
    defaults: { _controller: TakeATicketBundle:Management:index }
    methods:  [GET]

help:
    path:     /help/{section}
    defaults: { _controller: TakeATicketBundle:Management:help, section: 'readme' }
    methods:  [GET]

