-- One statement per line in order for tests to use this file

INSERT INTO instruments (name, abbreviation, iconHtml) VALUES ('Vocals', 'V', '<img src="local/rb-mic.png" class="instrumentIcon"/>');
INSERT INTO instruments (name, abbreviation, iconHtml) VALUES ('Guitar', 'G', '<img src="local/rb-guitar.png" class="instrumentIcon"/>');
INSERT INTO instruments (name, abbreviation, iconHtml) VALUES ('Bass', 'B', '<img src="local/rb-bass.png" class="instrumentIcon"/>');
INSERT INTO instruments (name, abbreviation, iconHtml) VALUES ('Drums', 'D', '<img src="local/rb-drums.png" class="instrumentIcon"/>');
INSERT INTO instruments (name, abbreviation, iconHtml) VALUES ('Keyboard', 'K', '<img src="local/rb-keys.png" class="instrumentIcon"/>');

INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (29, 'The Acro-brats', 'Day Late, Dollar Short', 1, 'E2F9FA');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (39, 'Aerosmith', 'Train Kept A Rollin'' (Cover version)', 1, '5CC438');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (83, 'Anarchy Club', 'Blood Doll', 1, '68442A');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (114, 'Bang Camaro', 'Pleasure (Pleasure)', 1, 'DE749E');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (118, 'Beastie Boys', 'Sabotage', 1, '657CEB');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (255, 'Black Sabbath', 'Paranoid (Cover version)', 1, 'E855D1');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (277, 'Blue Oyster Cult', '(Don''t Fear) The Reaper', 1, '12D9AB');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (311, 'Bon Jovi', 'Wanted Dead or Alive', 1, '502B78');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (318, 'Boston', 'Foreplay/Long Time', 1, 'E059B5');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (395, 'The Clash', 'Should I Stay or Should I Go', 1, 'FDC641');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (403, 'Coheed and Cambria', 'Welcome Home', 1, 'A7F47D');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (434, 'Crooked X', 'Nightmare', 1, '13853A');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (456, 'David Bowie', 'Suffragette City', 1, 'C13E0A');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (462, 'Death of the Cool', 'Can''t Let Go', 1, '20688B');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (467, 'Deep Purple', 'Highway Star', 1, '208E66');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (487, 'Die Toten Hosen', 'Hier Kommt Alex', 1, '51FF72');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (582, 'Faith No More', 'Epic', 1, 'D006F7');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (587, 'Fall Out Boy', 'Dead on Arrival', 1, '702E24');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (608, 'Flyleaf', 'I''m So Sick', 1, '502E95');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (614, 'Foo Fighters', 'Learn to Fly', 1, '734F78');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (645, 'Freezepop', 'Brainpower', 1, 'AEDE39');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (647, 'Garbage', 'I Think I''m Paranoid', 1, 'D3119A');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (748, 'The Hives', 'Main Offender', 1, 'FCF78B');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (750, 'Hole', 'Celebrity Skin', 1, '5DC072');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (751, 'Honest Bob and the Factory-to-Dealer Incentives', 'I Get By', 1, '8737BF');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (810, 'Jet', 'Are You Gonna Be My Girl', 1, '68F7DD');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (879, 'Journey', 'Any Way You Want It', 1, '9715FC');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (924, 'The Killers', 'When You Were Young', 1, '089DC0');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (929, 'KISS', 'Detroit Rock City', 1, '318042');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (941, 'The Konks', '29 Fingers', 1, 'A87C46');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1050, 'Metallica', 'Enter Sandman', 1, '384550');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1099, 'Molly Hatchet', 'Flirtin'' with Disaster', 1, '5D1FB6');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1101, 'The Mother Hips', 'Time We Had', 1, 'A7B091');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1119, 'Mountain', 'Mississippi Queen (Cover version)', 1, 'F65DF8');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1141, 'The New Pornographers', 'Electric Version', 1, '39E60A');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1164, 'Nine Inch Nails', 'The Hand That Feeds', 1, 'CEC8D2');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1171, 'Nirvana', 'In Bloom', 1, 'BD2B12');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1195, 'OK Go', 'Here It Goes Again', 1, 'B6DEA9');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1205, 'The Outlaws', 'Green Grass and High Tides (Cover version)', 1, '46B38C');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1295, 'Pixies', 'Wave of Mutilation', 1, '4B98E3');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1308, 'The Police', 'Next to You', 1, '60A41C');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1365, 'Queens of the Stone Age', 'Go with the Flow', 1, '73731E');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1385, 'R.E.M.', 'Orange Crush', 1, '66E8DE');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1392, 'Radiohead', 'Creep', 1, '813CB8');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1403, 'Ramones', 'Blitzkrieg Bop', 1, 'DF63CC');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1468, 'The Rolling Stones', 'Gimme Shelter', 1, '59C66A');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1492, 'Rush', 'Tom Sawyer (Cover version)', 1, 'DF65F7');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1542, 'Smashing Pumpkins', 'Cherub Rock', 1, '6845A4');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1627, 'Stone Temple Pilots', 'Vasoline', 1, '36BFA6');
INSERT INTO songs (id, artist, title, sourceId, codeNumber) VALUES (1631, 'The Strokes', 'Reptilia', 1, '69D71E');
