INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (29, 'The Acro-brats', 'Day Late, Dollar Short', 'Rock Band', 1, 0, 'E2F9FA');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (39, 'Aerosmith', 'Train Kept A Rollin'' (Cover version)', 'Rock Band', 1, 0, '5CC438');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (83, 'Anarchy Club', 'Blood Doll', 'Rock Band', 1, 0, '68442A');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (114, 'Bang Camaro', 'Pleasure (Pleasure)', 'Rock Band', 1, 0, 'DE749E');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (118, 'Beastie Boys', 'Sabotage', 'Rock Band', 1, 0, '657CEB');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (255, 'Black Sabbath', 'Paranoid (Cover version)', 'Rock Band', 1, 0, 'E855D1');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (277, 'Blue Oyster Cult', '(Don''t Fear) The Reaper', 'Rock Band', 1, 0, '12D9AB');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (311, 'Bon Jovi', 'Wanted Dead or Alive', 'Rock Band', 1, 0, '502B78');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (318, 'Boston', 'Foreplay/Long Time', 'Rock Band', 1, 0, 'E059B5');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (395, 'The Clash', 'Should I Stay or Should I Go', 'Rock Band', 1, 0, 'FDC641');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (403, 'Coheed and Cambria', 'Welcome Home', 'Rock Band', 1, 0, 'A7F47D');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (434, 'Crooked X', 'Nightmare', 'Rock Band', 1, 0, '13853A');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (456, 'David Bowie', 'Suffragette City', 'Rock Band', 1, 0, 'C13E0A');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (462, 'Death of the Cool', 'Can''t Let Go', 'Rock Band', 1, 0, '20688B');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (467, 'Deep Purple', 'Highway Star', 'Rock Band', 1, 0, '208E66');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (487, 'Die Toten Hosen', 'Hier Kommt Alex', 'Rock Band', 1, 0, '51FF72');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (582, 'Faith No More', 'Epic', 'Rock Band', 1, 0, 'D006F7');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (587, 'Fall Out Boy', 'Dead on Arrival', 'Rock Band', 1, 0, '702E24');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (608, 'Flyleaf', 'I''m So Sick', 'Rock Band', 1, 0, '502E95');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (614, 'Foo Fighters', 'Learn to Fly', 'Rock Band', 1, 0, '734F78');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (645, 'Freezepop', 'Brainpower', 'Rock Band', 1, 0, 'AEDE39');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (647, 'Garbage', 'I Think I''m Paranoid', 'Rock Band', 1, 0, 'D3119A');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (748, 'The Hives', 'Main Offender', 'Rock Band', 1, 0, 'FCF78B');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (750, 'Hole', 'Celebrity Skin', 'Rock Band', 1, 0, '5DC072');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (751, 'Honest Bob and the Factory-to-Dealer Incentives', 'I Get By', 'Rock Band', 1, 0, '8737BF');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (810, 'Jet', 'Are You Gonna Be My Girl', 'Rock Band', 1, 0, '68F7DD');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (879, 'Journey', 'Any Way You Want It', 'Rock Band', 1, 0, '9715FC');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (924, 'The Killers', 'When You Were Young', 'Rock Band', 1, 0, '089DC0');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (929, 'KISS', 'Detroit Rock City', 'Rock Band', 1, 0, '318042');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (941, 'The Konks', '29 Fingers', 'Rock Band', 1, 0, 'A87C46');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1050, 'Metallica', 'Enter Sandman', 'Rock Band', 1, 0, '384550');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1099, 'Molly Hatchet', 'Flirtin'' with Disaster', 'Rock Band', 1, 0, '5D1FB6');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1101, 'The Mother Hips', 'Time We Had', 'Rock Band', 1, 0, 'A7B091');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1119, 'Mountain', 'Mississippi Queen (Cover version)', 'Rock Band', 1, 0, 'F65DF8');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1141, 'The New Pornographers', 'Electric Version', 'Rock Band', 1, 0, '39E60A');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1164, 'Nine Inch Nails', 'The Hand That Feeds', 'Rock Band', 1, 0, 'CEC8D2');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1171, 'Nirvana', 'In Bloom', 'Rock Band', 1, 0, 'BD2B12');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1195, 'OK Go', 'Here It Goes Again', 'Rock Band', 1, 0, 'B6DEA9');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1205, 'The Outlaws', 'Green Grass and High Tides (Cover version)', 'Rock Band', 1, 0, '46B38C');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1295, 'Pixies', 'Wave of Mutilation', 'Rock Band', 1, 0, '4B98E3');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1308, 'The Police', 'Next to You', 'Rock Band', 1, 0, '60A41C');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1365, 'Queens of the Stone Age', 'Go with the Flow', 'Rock Band', 1, 0, '73731E');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1385, 'R.E.M.', 'Orange Crush', 'Rock Band', 1, 0, '66E8DE');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1392, 'Radiohead', 'Creep', 'Rock Band', 1, 0, '813CB8');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1403, 'Ramones', 'Blitzkrieg Bop', 'Rock Band', 1, 0, 'DF63CC');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1468, 'The Rolling Stones', 'Gimme Shelter', 'Rock Band', 1, 0, '59C66A');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1492, 'Rush', 'Tom Sawyer (Cover version)', 'Rock Band', 1, 0, 'DF65F7');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1542, 'Smashing Pumpkins', 'Cherub Rock', 'Rock Band', 1, 0, '6845A4');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1627, 'Stone Temple Pilots', 'Vasoline', 'Rock Band', 1, 0, '36BFA6');
INSERT INTO songs (id, artist, title, source, hasHarmony, hasKeys, codeNumber) VALUES (1631, 'The Strokes', 'Reptilia', 'Rock Band', 1, 0, '69D71E');
